### ISSUE TITLE
Setup unit test locally and CI test 

### ISSUE THREAD

**Issue by risenW** [datopian/portal-experiment#6]
Setup unit and end-to-end test in project

## Acceptance
* [x]  I have unit tests set up **Done** see https://github.com/datopian/portal-experiment/pull/8
* [x] I have added some test for functions in the lib folder
* [x] I have a test for each component in the components folder
* [x] I have tests for pages
* [ ] I have set up the test in repo CI

![Screen Shot 2021-03-02 at 2 34 20 PM](https://user-images.githubusercontent.com/29900845/109656156-69636600-7b64-11eb-95e7-2856aa252cc7.png)

## Task
* [x] Set up unit test using jest
* [x] Write tests for:
   * [x] functions in libs
        * [x] utils
        * [x] dataset 
   * [x] components
       * [x] Chart
       * [x] Table 
   * [x] pages
       * [x] index
 * [ ] Set up test in repo CI
